[project]
name = "cs336_basics"
version = "26.0.0"
description = "CS336 Assignment 1"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "torch>=2.4.0",
    "pytorch-triton-xpu; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "triton-xpu; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "einops>=0.8",      # tensor operations
    "einx>=0.4",        # more general tensor operations
    "jaxtyping>=0.3",   # type hints for pytorch/jax/numpy
    "numpy>=2.4",
    "psutil>=7",
    "pytest>=9.0",
    "pytest-timeout",
    "regex>=2026.3.32", # more powerful regex than the builtin `re` module
    "tiktoken>=0.12.0",
   "tqdm",
    "wandb>=0.25",
    "ty>=0.0.26",
    "ruff>=0.15.8",
    "matplotlib",
    "tensorboard",
    "tbparse>=0.0.9",
    "seaborn>=0.13.2",
    "poethepoet",
    "openvino",
]


[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "cs336_basics"
module-root = ""

[tool.uv]
package = true
python-preference = "managed"

# Constrain uv's resolver to ONLY solve for these two platforms
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

# Declare the PyTorch XPU index as explicit
[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

# Direct Linux torch resolution to the XPU index
[tool.uv.sources]
torch = [
    { index = "pytorch-xpu", marker = "sys_platform == 'linux'" },
]
triton-xpu = [
    { index = "pytorch-xpu", marker = "sys_platform == 'linux'" },
]
pytorch-triton-xpu = [
    { index = "pytorch-xpu", marker = "sys_platform == 'linux'" },
]

[tool.setuptools.packages.find]
include = ["cs336_basics*"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
addopts = "-s"

[tool.ruff]
line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
# Also ignore `E402` in all `__init__.py` files.
"__init__.py" = ["E402", "F401", "F403", "E501"]

[tool.ruff.lint]
extend-select = ["UP"]
ignore = ["F722"]

[tool.poe.tasks.run-xpu]
help = "Run a python script with XPU library paths set"
cmd = "python ${script} ${args}"

# Set the XPU environment variables for this task
# examples to run
# uv run poe run-xpu runs/try.py
# uv run poe run-xpu runs/tinystories_example.py
# uv run poe run-xpu runs/traincmd.py --name "001" --tokenfile=TinyStoriesV2-GPT4 --maxsteps 10000 --batch_size 128 --contextlen 256
env = { LD_LIBRARY_PATH = "./.venv/lib:./.venv/lib/python3.10/site-packages/torch/lib" }

# Define the arguments poe should expect from your command line
args = [
  { name = "script", positional = true, required = true, help = "The python script to run" },
  { name = "args", positional = true, multiple = true, help = "Arguments to pass to the script" }
]

